<?php 
$comp = $adminuser->getComponent(_USER);?>
<? if ($Page == "Home") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="<? if (isset($isVerified) && !$isVerified) {?>loginFailed();<? }?><? if (isset($GoTo)) {?>goTo('<?=$GoTo?>');<? }?>">
<? } else if ($Page == "ShoppingCart") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="<? if (array_search("User Account",$comp) > -1 && (WebContent::getPropertyValue("user_account") == "" || WebContent::getPropertyValue("user_account") == "yes") && !isset($user)) {?>signIn();<? }?>">
<? } else if ($Page == "WishList") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="<? if (array_search("User Account",$comp) > -1 && (WebContent::getPropertyValue("user_account") == "" || WebContent::getPropertyValue("user_account") == "yes") && $Action == "Add" && !isset($user)) {?>signIn();<? }?>">
<? } else if ($Page == "FindWishList") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="<? if ($found) {?>goToWishList();<? }?>">
<? } else if ($Page == "Account") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="<? if (!isset($user)) {?>signIn();<? }?>">
<? } else if ($Page == "RegistrationResult") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="<? if ($isSuccess) {?>signIn();<? } else {?>registrationFailed();<? }?>">
<? } else if ($Page == "SignOut") {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>" onLoad="signOut();">
<? } else {?>
<body text="<?=WebContent::getPropertyValue("classic_3_font_color")?>" background="<?=WebContent::getPropertyValue("classic_3_bg_img")?>" link="<?=WebContent::getPropertyValue("classic_3_link_color")?>" vlink="<?=WebContent::getPropertyValue("classic_3_visited_link_color")?>" alink="<?=WebContent::getPropertyValue("classic_3_active_link_color")?>" bgcolor="<?=WebContent::getPropertyValue("classic_3_body_bgcolor")?>">
<? }?>